base_path = "~/dev/www"
write_to_disk = true

[content]
path = "content"

[[content.page_types]]
type = "post"
path = "posts"
default_template = "blogpost.html"

[[content.page_types]]
type = "page"
path = "pages"
default_template = "raw.html"

[[content.page_types]]
type = "asset"
path = "assets"
default_template = "raw.html"

[templates]
path = "templates"
