[env]
THEA_CACHE = false
THEA_PATH = "${HOME}/dev/thea/target/debug"

[tasks.default]
alias = "dev"

[tasks.dev]
install_crate = "watchexec"
command = "watchexec"
args = ["-r", "-i", "content/assets", "-s", "SIGKILL", "cargo make files_changed"]

[tasks.compile_sass]
script = ['''
echo -e "$(cat src/styles.frontmatter)\n$(sass src/styles.scss)" > content/assets/styles.css
''']

[tasks.start_server]
command = "${THEA_PATH}/thea"

[tasks.files_changed]
dependencies = ["compile_sass", "start_server"]
