[env]
THEA_PATH = "${HOME}/dev/thea/target/debug"

[tasks.watch_css]
command = "watchexec"
args = ["-w", "src/", "cargo make compile_css"]

[tasks.compile_css]
dependencies = ["run_tailwind", "run_purgecss", "run_csso", "merge_css_frontmatter"]

[tasks.run_tailwind]
command = "tailwind"
args = ["build", "src/styles.css", "--output", "src/tmp.css"]

[tasks.run_purgecss]
command = "purgecss"
args = ["--config", "purgecss.config.js", "--output", "src/"]

[tasks.run_csso]
command = "csso"
args = ["src/tmp.css", "--output", "src/tmp.css"]

[tasks.merge_css_frontmatter]
script = ['''
rm content/assets/styles.css
cat src/styles.frontmatter | cat - src/tmp.css > content/assets/styles.css
rm src/tmp.css
''']

[tasks.start_server]
env = { "THEA_ENV" = "development" }
command = "${THEA_PATH}/thea"
args = ["--dev"]
