[env]
THEA_PATH = "${HOME}/dev/thea/target/debug"

[tasks.default]
alias = "dev"

[tasks.dev]
run_task = { name = ["watch_css", "start_server"], parallel = true }

[tasks.watch_css]
install_crate = "watchexec"
command = "watchexec"
args = ["-w", "src/", "cargo make compile_css"]

[tasks.compile_css]
script = ['''
tailwind build src/styles.css --output content/assets/styles.css
purgecss --config purgecss.config.js --out content/assets/
csso content/assets/styles.css --output content/assets/styles.css
echo -e "$(cat src/styles.frontmatter)\n$(cat content/assets/styles.css)" > content/assets/styles.css
''']

[tasks.start_server]
env = { "THEA_ENV" = "development" }
command = "${THEA_PATH}/thea"
args = ["--dev"]
