[env]
THEA_PATH = "${HOME}/dev/thea/target/debug"

[tasks.watch_css]
command = "watchexec"
args = ["-w", "src/", "cargo make compile_css"]

[tasks.compile_css]
dependencies = ["run_tailwind", "run_purgecss", "run_csso", "merge_css_frontmatter"]

[tasks.run_tailwind]
command = "tailwind"
args = ["build", "src/styles.css", "--output", "content/assets/styles.css"]

[tasks.run_purgecss]
command = "purgecss"
args = ["--config", "purgecss.config.js", "--output", "content/assets/"]

[tasks.run_csso]
command = "csso"
args = ["content/assets/styles.css", "--output", "content/assets/styles.css"]

[tasks.merge_css_frontmatter]
script = ['''
cat src/styles.frontmatter | cat - content/assets/styles.css > temp && rm content/assets/styles.css && mv temp content/assets/styles.css
''']

[tasks.start_server]
env = { "THEA_ENV" = "development" }
command = "${THEA_PATH}/thea"
args = ["--dev"]
