[env]
THEA_CACHE = false
THEA_PATH = "${HOME}/dev/thea/target/debug"

[tasks.default]
alias = "dev"

[tasks.dev]
install_crate = "watchexec"
command = "watchexec"
args = ["-r", "-i", "content/assets", "-i", "logs", "-s", "SIGKILL", "cargo make files_changed"]

[tasks.compile_sass]
script = ['''
tailwind build src/styles.css --output content/assets/styles.css
purgecss --css content/assets/**/*.css --content .rendered/**/*.html --out content/assets/
csso content/assets/styles.css --output content/assets/styles.css
echo -e "$(cat src/styles.frontmatter)\n$(cat content/assets/styles.css)" > content/assets/styles.css
''']

[tasks.start_server]
command = "${THEA_PATH}/thea"
args = ["--dev"]

[tasks.files_changed]
dependencies = ["compile_sass", "start_server"]
