write_to_disk = true

[content]
path = "content"
syntax_theme = "Solarized (dark)"

[[content.page_types]]
type = "post"
path = "posts"
default_layout = "blogpost.html"

[[content.page_types]]
type = "page"
path = "pages"
default_layout = "base.html"

[[content.page_types]]
type = "docs"
path = "docs"
default_layout = "docs.html"

[[content.page_types]]
type = "asset"
path = "assets"
default_layout = "raw.html"

[templates]
path = "templates"

[templates.globals]
base_url = "http://127.0.0.1:8765"
title = "Elliot Jackson: Freelance software designer and developer"
desc = "I'm Elliot Jackson; I build software for a living and write about Swift, Rust, and other things."
